# For Haskell Packaging Guidelines see:
# - https://fedoraproject.org/wiki/Packaging:Haskell
# - https://fedoraproject.org/wiki/PackagingDrafts/Haskell

Name:           bustle
Version:        0.2.5
Release:        1%{?dist}
Summary:        D-Bus activity visualization

Group:          Development/Tools
License:        LGPLv2.1 and GPLv2+
URL:            http://hackage.haskell.org/package/%{name}
Source0:        http://hackage.haskell.org/packages/archive/%{name}/%{version}/%{name}-%{version}.tar.gz
# fedora ghc archs:
ExclusiveArch:  %{ix86} x86_64 ppc alpha sparcv9 ppc64
BuildRequires:  ghc-devel
# macros for building haskell packages
BuildRequires:  ghc-rpm-macros
BuildRequires:	ghc-cairo-devel
BuildRequires:	ghc-glib-devel
BuildRequires:	ghc-glade-devel
BuildRequires:	ghc-gtk-devel > 0.11
BuildRequires:	ghc-mtl-devel
BuildRequires:	ghc-pango-devel
BuildRequires:	ghc-parsec-devel

%description

Bustle draws sequence diagrams of D-Bus activity, showing signal
emissions, method calls and their corresponding returns, with
timestamps for each individual event and the duration of each method
call. This can help you check for unwanted D-Bus traffic, and pinpoint
why your D-Bus-based application isn't performing as well as you
like. It also provides statistics like signal frequencies and average
method call times.




%prep
%setup -q


%build
%ghc_bin_build


%install
%ghc_bin_install


%files
%defattr(-,root,root,-)
%doc LICENSE HACKING NEWS README
%attr(755,root,root) %{_bindir}/%{name}*


%changelog
* Sun Jun 26 2011 Adam Huffman <bloch@verdurin.com> - 0.2.5-1
- add missing BRs

* Sun Jun 26 2011 Fedora Haskell SIG <haskell-devel@lists.fedoraproject.org> - 0.2.5-0
- initial packaging for Fedora automatically generated by cabal2spec-0.22.7
